### ISSUE TITLE
Dates are wrong -> schedule

### ISSUE THREAD

**Issue by SaeLLo** [mainmatter/eurorust.eu#368]
It says 13th and 14th of October instead 12th and 13th

**Comment by oscard0m** [comment]
@SaeLLo I don't see that:
- https://eurorust.eu/
- https://eurorust.eu/schedule/day/1/
- https://eurorust.eu/schedule/day/2/

Is it possible the issue is already solved?

**Comment by SaeLLo** [comment]
It is solved.
