### ISSUE TITLE
Add workshops and other activities to schedule overview

### ISSUE THREAD

**Issue by marcoow** [mainmatter/eurorust.eu#469]
Let's add the workshops to the schedule overview:
![Bildschirmfoto 2024-05-15 um 11 07 14](https://github.com/mainmatter/eurorust.eu/assets/1510/ac4d885e-efe4-41aa-9780-21acacdc3b34)

I'd say we can just put them on top of the _"The EuroRust workshops will take place in a separate venue in the city center."_ text:

```
10:00 - 16:00: Rediscovering the Future: a deep dive into async Rust
10:00 - 16:00: Testing in Rust: going beyond the basics
10:00 - 16:00: Introduction to Diesel: basic and advanced concepts in practice
```

and make the workshop titles links to the respective workshops details pages

We should also add the walking tours on the day before and after the conference to the overview. For that, we should change the title _"Workshop Day - Oct. 9th, 2024"_ to _"Pre Conference Day - Oct. 9th, 2024"_ and add the walking tours below that, e.g. (I'm not sure what the exact times and descriptions are – we can use this as a placeholder for now):

```
12:00 - 14:00: Vienna walking tour
```

and add another section _"Post Conference Day - Oct. 12th, 2024"_ with the working tours happening on that day below

**Comment by nchan0154** [comment]
@marcoow I was double checking the live site and I noticed that within the activity cards, the speaker links are now no longer clickable, but I believe the workshop mentors don't have pages? Would you prefer that I remove the link from activity cards entirely, or fix the links for the activity cards/add workshop mentor pages?

**Comment by marcoow** [comment]
I wanted the workshop mentor names to look the same as the speakers' names in the talks schedule. The mentors don't have their own pages and their name appears within the outer box that links to the workshop details page anyway so that seems fine?

**Comment by nchan0154** [comment]
Ok yeah, the full speaker bio also appears on individual talk pages so it should be ok to leave as is then!

**Comment by marcoow** [comment]
done via #501
