### ISSUE TITLE
Add `og:image`s

### ISSUE THREAD

**Issue by marcoow** [mainmatter/eurorust.eu#505]
We should add `og:image`s so people get proper previews when linking to talks on social media.

**Comment by IdeliaRisella** [comment]
![og-image-Adam Chalmers](https://github.com/mainmatter/eurorust.eu/assets/173136359/38022cfb-4d46-43cc-be7a-c376daae1470)
![og-image-Aida Getoeva](https://github.com/mainmatter/eurorust.eu/assets/173136359/65bff5b3-31f3-4dcf-ad50-b5a9b7cc44d1)
![og-image-Arthur Pastel](https://github.com/mainmatter/eurorust.eu/assets/173136359/44a5e388-579d-4002-8ecd-b3ff29310e58)
![og-image-Attilla Haraszti](https://github.com/mainmatter/eurorust.eu/assets/173136359/7139bd32-8183-41f0-946c-3efe1298337a)
![og-image-Boxy Uwu](https://github.com/mainmatter/eurorust.eu/assets/173136359/b7988736-49cc-4e88-8bd1-750731772694)
![og-image-Charlie Marsh](https://github.com/mainmatter/eurorust.eu/assets/173136359/ff423ffd-cefb-43e2-b0bf-c3c2cff23513)
![og-image-David Peherstorfer](https://github.com/mainmatter/eurorust.eu/assets/173136359/dc4c5d68-899d-4feb-8505-d753947b4e5a)
![og-image-Francois Mockers](https://github.com/mainmatter/eurorust.eu/assets/173136359/7439b8f3-d488-4413-ac57-58aa030b4a4a)
![og-image-Jon Gjengset](https://github.com/mainmatter/eurorust.eu/assets/173136359/36d59968-1515-462c-a4d5-a883bbc83f58)
![og-image-Jonathan Pallant](https://github.com/mainmatter/eurorust.eu/assets/173136359/04a9550c-575d-4844-b001-e2b8ad2a0477)
![og-image-Lukas Wirth](https://github.com/mainmatter/eurorust.eu/assets/173136359/965d3134-3544-4193-877a-fa62ec465810)
![og-image-Matthias Heiden](https://github.com/mainmatter/eurorust.eu/assets/173136359/a1dd2c15-e972-44c4-981c-90a852e130f5)
![og-image-Nikita Lapkov](https://github.com/mainmatter/eurorust.eu/assets/173136359/c643dcad-86a6-43e1-a9cf-9406ff7d0693)
![og-image-Niklas Korz](https://github.com/mainmatter/eurorust.eu/assets/173136359/560d5a0a-835c-4b05-b44d-619de4fd6a7f)
![og-image-Orhun Parmaksız](https://github.com/mainmatter/eurorust.eu/assets/173136359/84af6a7a-233c-4d36-b2b9-65a4cd192ccf)
![og-image-Predrag Gruevski](https://github.com/mainmatter/eurorust.eu/assets/173136359/a1f3483d-449f-4685-804a-0a43a0b21769)
![og-image-Sam Van Overmeire](https://github.com/mainmatter/eurorust.eu/assets/173136359/07e2d14e-5f1f-4ff0-aa22-b6ce03e91678)
![og-image-Samuel Moelius](https://github.com/mainmatter/eurorust.eu/assets/173136359/eca26175-9017-4224-9615-bedec05098f8)
![og-image-Sasha Pourcelot](https://github.com/mainmatter/eurorust.eu/assets/173136359/c320343f-d9df-424a-bb92-d2311b2dd11f)
![og-image-Scott Chacon](https://github.com/mainmatter/eurorust.eu/assets/173136359/d57c6c03-94c6-44ae-9d31-797ba2454b6d)
![og-image-Victor Ciura](https://github.com/mainmatter/eurorust.eu/assets/173136359/89e899e8-7cfc-4844-b559-7ffd0faff766)
![og-image-Vitaly Bragilevsky](https://github.com/mainmatter/eurorust.eu/assets/173136359/6daaa560-c1a7-4c16-9e44-cc42413f5007)
![og-image-Björn Wieczoreck](https://github.com/mainmatter/eurorust.eu/assets/173136359/07a405f8-878b-419c-8f6e-ab484e31c7f6)
