### ISSUE TITLE
Missing letter on David Peherstorfer's talk title

### ISSUE THREAD

**Issue by IdeliaRisella** [mainmatter/eurorust.eu#517]
His title is supposed to have the word "Rustacean" but currently, missing the letter 'N' at the end of it. I don't know if I should change it myself, therefore I am just putting down an issue. 

<img width="1254" alt="Screenshot 2024-07-22 at 09 00 00" src="https://github.com/user-attachments/assets/e0f16494-beaa-4d65-986d-5c4b7bb5c903">

**Comment by marcoow** [comment]
please can you attach the updated image here?

**Comment by IdeliaRisella** [comment]
Yes, this is the updated og:image. The title to his abstract on the website also needs an update. Thank you 😊

![og-image-David Peherstorfer](https://github.com/user-attachments/assets/5861aeb0-0ffe-4c70-881d-2d1b13229f00)
image.
