### ISSUE TITLE
Media Partner Section

### ISSUE THREAD

**Issue by IdeliaRisella** [mainmatter/eurorust.eu#533]
Hi all, help is needed again for marketing purposes. We're now closing deals with a few media partners. Part of the deal is giving their logo a space on eurorust website. Is it possible to add a Media Partner section below the sponsors (maybe)? The size, I believe, should be smaller than the sponsors / paying partners.

Thank you for your help. I will give the logos for the partner as soon as they're available 😊

**Comment by IdeliaRisella** [comment]
![devituk-rectangle-white](https://github.com/user-attachments/assets/8c10d7d8-ad91-4a72-bbfe-24208670672d)
![Logo_Germany_PNG](https://github.com/user-attachments/assets/fab1a568-7d5a-4042-bc84-338e07458a35)
![rust-linz-logo-white](https://github.com/user-attachments/assets/76400326-ff54-40e5-acad-3593854bdf08)

Here are the 3 logos that are ready to put on media partner section. For the Woman in Tech, they didn't have the all white version of the logo. @umbrellarocket Would you help and edit this logo to all white just like the other logos on the website? Thank you so much

**Comment by marcoow** [comment]
done
