### ISSUE TITLE
Put information on workshop venue on the website

### ISSUE THREAD

**Issue by marcoow** [mainmatter/eurorust.eu#534]
We're currently only saying the workshop venue is a different one in the city center. We should add the details, see https://www.notion.so/mainmatter/Venues-7c607961b70e465896a50e6df3b21dbe?pvs=4#5b80e8dd5073453fa68c412b32d4b39d

**Comment by umbrellarocket** [comment]
See https://github.com/mainmatter/eurorust.eu/compare/main...add-hulks-and-venue-details?expand=1
