### ISSUE TITLE
Info about HULKs Robo-soccer team on conference days

### ISSUE THREAD

**Issue by IdeliaRisella** [mainmatter/eurorust.eu#558]
Please help putting the information on both days of conference regarding HULKs Robo-soccer team exhibition. Please look at the notion page here: https://www.notion.so/mainmatter/Announce-http-hulks-de-robo-soccer-team-179ee00d55014b4abc2e1cb8fd592833?pvs=4

Photo to use:
![240748037_6046847068720842_38655145853045758_n](https://github.com/user-attachments/assets/08dcdd1c-4b60-409a-a148-36a569f3a0fc)

Photo source: Photo by HULKs Team on instagram.com/hulks_tuhh/ 

Copy recommendation:
Title -> Meet the Rust-programmed robo-soccer team!
Body -> The HULKs RoboCup SPL Team is coming to EuroRust. Don’t miss their live demos, code showcases, and debugging tool sessions. 🤖

**Comment by umbrellarocket** [comment]
See https://github.com/mainmatter/eurorust.eu/compare/main...add-hulks-and-venue-details?expand=1
